apiVersion: v1
kind: Service
metadata:
  annotations:
  name: pods-list 
  namespace: pods-list
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pods-list
  type: ClusterIP